### PR TITLE
Completed ui & vr polishes

### PR DESCRIPTION
**Pull request by tyherox**
UI Changes
- added Search bar
- added desktop-only scroll prevention on modal components (will do mobile soon)
- temporary disable of  login check due to issues with Oauth
- temporary disable of preview component engine instance (see in code todo) 

VR Changes
- added a landscape mode check on fullscreen VR entry for mobile devices
- added image previews for custom scene and sprites
- data structure change of sprite from single [activesprite] to [type: (‘custom’ or ‘default’) src: (SRC)]
- fixed glitch where play button is show even when no game is active 
- fixed glitch where custom sprites did not appear
- fixed glitch where resetting custom user background was not shown

### CODE REVIEW

**Comment by shchoi22** [comment]
@tyherox Just pulled down the branch for testing but I am getting blank screen on home page with console error: `Error: permission_denied at /posts: Client doesn't have permission to access the desired data.` This is probably due to https://github.com/cubros/vread/pull/12/files#diff-59d2d4ad0bd8a50144b6d6b30d01ecccR49.

**Comment by tyherox** [comment]
@shchoi22  I couldn't replicate your error initially but found out it appeared only on other browsers I haven't developed on. The problem seemed to have been because of my decision to cut out the login portion at the router. I added it back and now other browsers work as well!

**Comment by shchoi22** [comment]
@tyherox So to clarify, the reason why other browser was able to replicate the issue vs. the main browser you use to develop (I assume this is Chrome) is that other browsers did not have authentication token cached in local storage by the browser for other browsers. Your main browser already had authentication token cached and did not require to be on login screen at home page. 

Firebase stores auth token in local storage to keep authentication state in event of browser reload.

👍 Ready to be merged.

**Comment by tyherox** [comment]
Yup I think so! I'll go ahead and merge it.

**Pull request merged**
